{% set name = "backports.tarfile" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backports.tarfile-{{ version }}.tar.gz
  url: https://github.com/jaraco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 52bdbbde19d8f679c008ba92df49f84363fdb7913d93227c3ae49e3e49bef7e4

build:
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - toml
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - backports.tarfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/backports.tarfile
  summary: Backport of CPython tarfile module
  # No description available
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/jaraco/backports.tarfile
  doc_url: https://github.com/jaraco/backports.tarfile

extra:
  recipe-maintainers:
    - carlodri
