{% set name = "backports.tarfile" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backports.tarfile-{{ version }}.tar.gz
  sha256: 2688f159c21afd56a07b75f01306f9f52c79aebcc5f4a117fb8fbb4445352c75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=56
    - setuptools-scm >=3.4.1
    - pip
    - backports
  run:
    - python >=3.8
    - backports

test:
  imports:
    - backports.tarfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/backports.tarfile
  summary: Backport of CPython tarfile module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
